apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns
  labels:
    name: minio-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio-ns
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ROOT_USER
              value: "minio"
            - name: MINIO_ROOT_PASSWORD
              value: "9606ece0896b8c8cdafee7f044807d665b4ae2f5"
          args:
            - server
            - /data
            - --console-address
            - ":9090"
          ports:
            - containerPort: 9000
            - containerPort: 9090
          volumeMounts:
            - mountPath: /data
              name: data

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio-ns
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
    - name: console
      port: 9090
      targetPort: 9090